# Generated by Django 4.2.7 on 2023-11-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('noteId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=200)),
                ('noteContent', models.TextField()),
            ],
        ),
    ]
