# Generated by Django 4.2.7 on 2023-11-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unitId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('unitName', models.CharField(max_length=200)),
            ],
        ),
    ]
